config/routes.rb
Rails.application.routes.draw do
  root to: 'groups#index'

  devise_for :users

  resources :groups
  resources :messages,only: [:create]

  resources :user_to_groups, only:[:create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  
  has_many :messages, dependent: :destroy
  has_many :user_to_groups
  has_many :users, through: :user_to_groups
  
end

app/models/message.rb
class Message < ApplicationRecord
  
  belongs_to :user
  belongs_to :group
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :user_to_groups
         has_many :groups, through: :user_to_groups
         has_many :messages, dependent: :destroy
end

app/models/user_to_group.rb
class UserToGroup < ApplicationRecord
  
  belongs_to :user
  belongs_to :group
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups=Group.all

  end

  def edit
  end

  def new
    @group=Group.new
  end

  def show
    @group=Group.find(params[:id])
    @users=@group.users
    @message=Message.new
    @messages=@group.messages.all
  end

  def update
  end

  def create
    @group=Group.new(group_params)
    @group.save
    redirect_to root_path
  end

  def destroy
  end

   private

  def group_params
    params.require(:group).permit(:name)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @message=Message.new(message_params)
    @message.save
    redirect_to request.referer
  end

   private

  def message_params
    params.require(:message).permit(:content,:user_id,:group_id)
  end

end

app/controllers/user_to_groups_controller.rb
class UserToGroupsController < ApplicationController
  
  def create
    @bridge=UserToGroup.new(user_id: current_user.id,group_id: params[:id])
    @bridge.save
    
  redirect_to root_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/user_to_groups_helper.rb
module UserToGroupsHelper
end

app/views/groups/edit.html.erb
<h1>Groups#edit</h1>
<p>Find me in app/views/groups/edit.html.erb</p>

app/views/groups/index.html.erb
<h1>Groups#index</h1>
<p>Find me in app/views/groups/index.html.erb</p>


<% @groups.each do |group|%>
 <%=link_to "#{group.name}",group_path(group) %>
 <%=link_to "参加する",user_to_groups_path(id: group.id),method: :post %>
<%end%>

app/views/groups/new.html.erb
<h1>Groups#new</h1>
<p>Find me in app/views/groups/new.html.erb</p>


<%= form_with model: @group do|f|%>
<%=f.text_field :name %>
<%= f.submit '作成' %>
<%end%>

app/views/groups/show.html.erb
<h1><%= @group.name %></h1>
<p>Find me in app/views/groups/show.html.erb</p>


<%@users.each do |user|%>
<%=user.email%>
<%end%>

<%=form_with model: @message do |f|%>
 <%= f.text_field :content%>
 <%= f.hidden_field :group_id, :value => @group.id %>
 <%= f.hidden_field :user_id, :value => current_user.id %>
 <%= f.submit '送信' %>
<%end%>


<%@messages.each do |message|%>
 <%=message.content%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RevealChatPrc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=link_to "新規作成", new_group_path%>
    <%=link_to "一覧", groups_path%>
    
    <%= yield %>
  </body>
</html>